### ISSUE TITLE
Fix issue with downloading short clips via HLS

### ISSUE THREAD

**Issue by TravisCouture** [twelvelabs-io/tl-jockey#25]
When downloading short clips via HLS with `ffmpeg` sometimes seeking doesn't behave as expected even with the `accurate_seek` flag enabled by default.

**Comment by DmitriiTsy** [comment]
I used this type of prompts for testing all of the edge cases here : 

Using index [OurTwelveLabsIndexHere] please follow these steps: 1. Find a touchdown video in the index and select a 5-second segment that includes the moment the player crosses the goal line. 2. From this 5-second segment, create three shorter clips: a. A 0.5-second clip starting exactly when the player's foot touches the goal line. b. A 1-second clip starting 2 seconds into the 5-second segment. c. A 0.75-second clip from the very end of the 5-second segment. 3. Combine these three clips into a single video in this order: b, a, c (the 1-second clip, then the 0.5-second clip, then the 0.75-second clip). 4. Name the output file 'precise_short_clips_test.mp4'.

**Comment by DmitriiTsy** [comment]
Should we use your last hot fix for it for now ? @TravisCouture 

https://github.com/twelvelabs-io/tl-jockey/commit/376ab45e2cbb1c43d844402a6b806dac1bbc3d33
