### ISSUE TITLE
Modify Union type checking across codebase.

### ISSUE THREAD

**Issue by TravisCouture** [twelvelabs-io/tl-jockey#28]
In older versions of Python the `|` operator cannot be overloaded to use `Union[Class A | Class B]`. To address this we can migrate to versions safe type checking: `Union[Class A, Class B]`

**Comment by james-le-twelve-labs** [comment]
This issue has been resolved by this commit: https://github.com/twelvelabs-io/tl-jockey/commit/9bf99c8970b8fa1d17f83ae144a58f94e0faca08
