### ISSUE TITLE
Fix video write directory when running in the LangGraph API server.

### ISSUE THREAD

**Issue by TravisCouture** [twelvelabs-io/tl-jockey#33]
Right now the way the environment variables are set up in [example.env](https://github.com/twelvelabs-io/tl-jockey/blob/main/example.env) and [compose.yaml](https://github.com/twelvelabs-io/tl-jockey/blob/main/compose.yaml) when Jockey is running within the LangGraph API server container, it is trying to write directly to the host machine path instead of the local container path that is a volume mount. This prevents video from being saved due to the directory not existing.

TODO:

- [ ] Research the best way to deal with this issue.

**Comment by kingsotn-twelve** [comment]
this has been solved in #86
