### ISSUE TITLE
Add configuration for LangChain license key.

### ISSUE THREAD

**Issue by TravisCouture** [twelvelabs-io/tl-jockey#38]
Since LangGraph has been released to close beta, it now requires an API key to use the server version of Jockey. 

https://www.langchain.com/pricing

- [ ] Add documentation for this
- [ ] Update `example.env` to show this

### Discussed in https://github.com/twelvelabs-io/tl-jockey/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **nolandubeau** July  4, 2024</sup>
Hello,  

When I startup the langraph-api server I receive the following error:

langgraph-api-1       | 2024-07-05 01:02:07,895:ERROR:uvicorn.error Application startup failed. Exiting.
langgraph-api-1       | 2024-07-05 01:02:21,180:INFO:uvicorn.error Started server process [1]
langgraph-api-1       | 2024-07-05 01:02:21,180:INFO:uvicorn.error Waiting for application startup.
langgraph-api-1       | 2024-07-05 01:02:21,180:ERROR:uvicorn.error Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 18, in lifespan
langgraph-api-1       | ValueError: License key is not valid
langgraph-api-1       |
langgraph-api-1       | 2024-07-05 01:02:21,180:ERROR:uvicorn.error Application startup failed. Exiting.

I am able to access the LangGraph debugger UI, however I do not see the jockey agent listed in the side panel navigation.  
I have added my OPENAI API key and TWELVE_LABS_API_KEY key to the .env file and have also set LLM_PROVIDER=OPENAI.

Is there an additional License key variable that needs to be set somewhere?

Thank you.</div>

**Comment by james-le-twelve-labs** [comment]
@TravisCouture We resolved this issue with this PR: https://github.com/twelvelabs-io/tl-jockey/pull/52
