### ISSUE TITLE
Provide HLS URLs for any JSON that contains a Video ID

### ISSUE THREAD

**Issue by TravisCouture** [twelvelabs-io/tl-jockey#40]
Currently, not every response that contains a Video ID has the associated HLS URL. This can make rendering on the frontend more complicated. In general, HLS URLs should always exist within any JSON with a Video ID.

**Comment by DmitriiTsy** [comment]
@TravisCouture  Hey Travis. If I understand correctly, the video_urls are being cut off somehow, right? We can't use it, correct? Like this one: https://deuqpmn4rs7j5.cloudfront.net/64014aa08e079b9c96f4a55c/659f397d9aba4f0b402f64a5/st


![Screenshot 2024-09-05 at 5 23 58 PM](https://github.com/user-attachments/assets/02d39e89-9ac9-4c7f-8429-a510c7cb1aee)
