### ISSUE TITLE
Versioning_issue => elegant solution

### ISSUE THREAD

**Issue by DmitriiTsy** [twelvelabs-io/tl-jockey#57]
"We should try to enforce pydantic field constraints wherever possible" 

https://docs.pydantic.dev/1.10/usage/schema/#unenforced-field-constraints

**Comment by DmitriiTsy** [comment]
I didn't get the same problem with this issue as before, so consider it fixed and working as expected @james-le-twelve-labs

**Comment by james-le-twelve-labs** [comment]
@DmitriiTsy Closed this issue.
